on:
  workflow_dispatch:
    branches: [main]
    
    
name: hello-world    

jobs:
  write-message:
    runs-on: ubuntu-latest
    steps:
      - name: print-message
        run: echo "Hello R World!"