on:
  workflow_dispatch:
    branches: [main]
    
    
name: hello-r-world    

jobs:
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      
      - name: print-message
        run: echo "Hello R World!"