on:
  workflow_dispatch:
    branches: [main]
    
    
name: 05-run-r-script-save-results

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: run-script
        run: |
          Rscript ghactions/05-r-script-save-results.R
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update files - by 05-r-script-save-results" || echo "No changes to commit"
          git push origin || echo "No changes to commit"